name: Sync to Hugging Face hub

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Set up Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Pull and resolve conflicts automatically
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git pull --allow-unrelated-histories --no-rebase https://Junior19:$HF_TOKEN@huggingface.co/spaces/Junior19/samantinita main || true
          git checkout --ours .
          git add -A
          git commit -m "Resolved merge conflicts using local version"

      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push https://Junior19:$HF_TOKEN@huggingface.co/spaces/Junior19/samantinita main
